version: "1.0"

services:
  db-dev:
    image: mysql:8.0.20
    container_name: sapiv-db-dev
    env_file: .env.dbdev
    restart: always
    volumes: 
      - /home/ubuntu/.dbdata-dev:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - dbdev
  
  web-be-dev:
    build: Web-Backend/sapiv
    container_name: sapiv-webbe-dev
    depends_on:
      - db-dev
    restart: always
    ports:
      - '8000:3000'
    networks:
      - dbdev
      - frontdev
  
  api-validator:
    build: API_validator_server
    container_name: sapiv-apivalidator-dev
    depends_on:
      - db-dev
    restart: always
    ports:
      - "8070:3000"
    networks:
      - dbdev

  web-fe-dev:
    build: Frontend/api_validator
    container_name: sapiv-webfe-dev
    depends_on:
      - web-be-dev
    restart: always
    ports:
      - '3000:3000'
    networks:
      - frontdev

networks:
  dbdev:
  frontdev: