pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('SonarQube Analysis') {
            steps {
                sh "${SONAR_SCANNER_HOME}/bin/sonar-scanner"
            }
        }

        stage('dockerizing'){
            steps{
                dir('Frontend/api_validator') {
                    sh 'docker build -t sapiv/webfe-image ./'
                }
            }

            post {
                success {
                    echo 'Dockerizing Success'
                }

                failure {
                    echo 'Dockerizing Failed'
                }
            }
        }

        stage('Deploy') {
            steps {
              script{
	            def container = sh(returnStdout: true, script: 'docker ps -a -q -f name=sapiv-webfe')

                if (container.trim().length() > 0) {
                  sh(returnStdout: false, script: 'docker ps -a -q -f name=sapiv-webfe && docker rm -f ' + container)
                }
              }

                sh 'docker run --privileged=true --name sapiv-webfe -d -p 80:3000 sapiv/webfe-image'
            }

            post {
                success {
                    echo 'Deploy Success'
                }

                failure {
                    echo 'Deploy Failed'
                }
            }
        }
    }
}