pipeline {
    agent any
    stages {
        stage('dockerizing'){
            steps{
                dir('API_validator_server') {
                    sh 'docker build -t sapiv/API-validator-image ./'
                }
            }

            post {
                success {
                    echo 'Dockerizing Success'
                }

                failure {
                    echo 'Dockerizing Failed'
                }
            }
        }

        stage('Deploy') {
            steps {
              script{
	            def container = sh(returnStdout: true, script: 'docker ps -a -q -f name=sapiv-API-validator')

                if (container.trim().length() > 0) {
                  sh(returnStdout: false, script: 'docker ps -a -q -f name=sapiv-API-validator && docker rm -f ' + container)
                }
              }

                sh 'docker run --privileged=true --name sapiv-API-validator -d -p 80:3000 sapiv/sapiv-API-validator-image'
            }

            post {
                success {
                    echo 'Deploy Success'
                }

                failure {
                    echo 'Deploy Failed'
                }
            }
        }
    }
}