version: "1.0"

services:
  db:
    image: mysql:8.0.20
    restart: always
    volumes: 
      - $HOME/db_data:/var/lib/mysql
    environment:
      # 임시
      MYSQL_DATABASE: 'db'
      # 임시
      MYSQL_USER: 'sapiv'
      # 임시
      MYSQL_PASSWORD: 'sapiv'
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  
  app:
    build: .
    depends_on:
      - db
    restart: always
    ports:
      - '8000:3000'